<div class="content-header">
    <h3 class="head-dashboard">Create ExtraWatch Account</h3>
</div>

<div id="extrawatch_account_creation_success" class="extrawatch_account_creation_success">
    <div class="check_inbox">
        <h2>Check your inbox for a verification email and get started on ExtraWatch.com</h2>
    </div>
    <div class="subheading">
        <h3>This helpful video will show you how to make the most of your Magento data.</h3>
    </div>
    <div class="video">
        <iframe src="http://player.vimeo.com/video/35349939?title=0&amp;byline=0&amp;portrait=0&amp;color=50b3dd" width="625" height="350" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe
>
    </div>
    <div class="send_note">
        <p><span>Have some questions?</span> Send a note to: <a href="mailto:support@extrawatch.com">support@extrawatch.com</a> or call us at +1 917 719 0255</p>
    </div>
</div>
