<div class="content-header">
    <h3 class="head-dashboard">Create ExtraWatch Account</h3>
</div>

<div id="extrawatch_account_creation" class="extrawatch_account_creation">

    <div class="extrawatch_signup_banner">
        <h1>Your ExtraWatch extension has been installed, now let's create your account.</h1>
    </div>

    <?php
      $error_email_response = Mage::getSingleton('adminhtml/session')->getErrorEmailResponseSessionVar();
      if (!empty($error_email_response)) {
        echo '<div id="error_response_message" class="error_response_message"><span>error response message</span> ' . $error_email_response . '</div>';
        Mage::getSingleton('adminhtml/session')->unsErrorEmailResponseSessionVar();
      }
    ?>

    <div class="extrawatch_signup_content clearfix">
        <form name="extrawatch_signupForm" method="post" id="extrawatch_signupForm" action="<? echo $this->getFormAction(); ?>" enctype="multipart/form-data">
            <input type="hidden" name="form_key" value="<? echo $this->getFormKey(); ?>" />
            <fieldset>
                <div class="extrawatch_signup_initial extrawatch_form_1">
                    <div class="create_act_field">
                        <label>First and Last Name</label>
                        <input type="text" id="fullName" name="fullName" value="" class="required-entry" tabindex="1" />
                    </div>
                    <div class="create_act_field">
                        <label>Primary Email Address</label>
                        <input type="email" id="email" name="email" value="" class="required-entry validate-email" tabindex="2" />
                    </div>
                    <div class="create_act_field">
                        <label>Create a Password</label>
                        <input type="password" id="password" name="password" class="required-entry validate-password" tabindex="3" />
                    </div>
                    <div class="create_act_field">
                        <label>Your Timezone</label>
                        <select id="timezone" name="timezone" class="validate-select" tabindex="4">
                        <option value="">Nearest Region or GMT</option>
                        <option value="US/Hawaii"  >-10:00 Hawaii</option>
                        <option value="US/Alaska"  >-9:00 Alaska</option>
                        <option value="US/Pacific"  >-8:00 Pacific Time (US &amp; Canada)</option>
                        <option value="US/Arizona"  >-7:00 Arizona</option>
                        <option value="US/Mountain"  >-7:00 Mountain Time (US &amp; Canada)</option>
                        <option value="US/Central"  >-6:00 Central Time (US &amp; Canada)</option>
                        <option value="US/Eastern"  >-5:00 Eastern Time (US &amp; Canada)</option>
                        <option value="US/East-Indiana"  >-5:00 Indiana (East)</option>
                        <option value="Etc/GMT-11"  >-11:00 International Date Line West</option>
                        <option value="Pacific/Midway"  >-11:00 Midway Island</option>
                        <option value="Pacific/Samoa"  >-11:00 Samoa</option>
                        <option value="America/Tijuana"  >-8:00 Tijuana</option>
                        <option value="America/Chihuahua"  >-7:00 Chihuahua</option>
                        <option value="America/Mazatlan"  >-7:00 Mazatlan</option>
                        <option value="Central America"  >-6:00 Central America</option>
                        <option value="America/Mexico_City"  >-6:00 Mexico City</option>
                        <option value="America/Monterrey"  >-6:00 Monterrey</option>
                        <option value="Canada/Saskatchewan"  >-6:00 Saskatchewan</option>
                        <option value="America/Bogota"  >-5:00 Bogota</option>
                        <option value="America/Lima"  >-5:00 Lima</option>
                        <option value="America/Caracas"  >-4:30 Caracas</option>
                        <option value="Canada/Atlantic"  >-4:00 Atlantic Time (Canada)</option>
                        <option value="America/La_Paz"  >-4:00 La Paz</option>
                        <option value="America/Santiago"  >-4:00 Santiago</option>
                        <option value="Canada/Newfoundland"  >-3:30 Newfoundland</option>
                        <option value="America/Buenos_Aires"  >-3:00 Buenos Aires</option>
                        <option value="Etc/GMT+3"  >-3:00 Greenland</option>
                        <option value="Etc/GMT+2"  >-2:00 Mid-Atlantic</option>
                        <option value="Atlantic/Azores"  >-1:00 Azores</option>
                        <option value="Atlantic/Cape_Verde"  >-1:00 Cape Verde Is.</option>
                        <option value="Africa/Casablanca"  >+0:00 Casablanca</option>
                        <option value="Europe/Dublin"  >+0:00 Dublin</option>
                        <option value="Europe/Lisbon"  >+0:00 Lisbon</option>
                        <option value="Europe/London"  >+0:00 London</option>
                        <option value="UTC"  >+0:00 UTC</option>
                        <option value="Europe/Amsterdam"  >+1:00 Amsterdam</option>
                        <option value="Europe/Belgrade"  >+1:00 Belgrade</option>
                        <option value="Europe/Berlin"  >+1:00 Berlin</option>
                        <option value="Europe/Bratislava"  >+1:00 Bratislava</option>
                        <option value="Europe/Brussels"  >+1:00 Brussels</option>
                        <option value="Europe/Budapest"  >+1:00 Budapest</option>
                        <option value="Europe/Copenhagen"  >+1:00 Copenhagen</option>
                        <option value="Europe/Ljubljana"  >+1:00 Ljubljana</option>
                        <option value="Europe/Madrid"  >+1:00 Madrid</option>
                        <option value="Europe/Paris"  >+1:00 Paris</option>
                        <option value="Europe/Prague"  >+1:00 Prague</option>
                        <option value="Europe/Rome"  >+1:00 Rome</option>
                        <option value="Europe/Sarajevo"  >+1:00 Sarajevo</option>
                        <option value="Europe/Skopje"  >+1:00 Skopje</option>
                        <option value="Europe/Stockholm"  >+1:00 Stockholm</option>
                        <option value="Europe/Vienna"  >+1:00 Vienna</option>
                        <option value="Europe/Warsaw"  >+1:00 Warsaw</option>
                        <option value="Europe/Zagreb"  >+1:00 Zagreb</option>
                        <option value="Europe/Athens"  >+2:00 Athens</option>
                        <option value="Europe/Bucharest"  >+2:00 Bucharest</option>
                        <option value="Africa/Cairo"  >+2:00 Cairo</option>
                        <option value="Africa/Harare"  >+2:00 Harare</option>
                        <option value="Europe/Helsinki"  >+2:00 Helsinki</option>
                        <option value="Europe/Istanbul"  >+2:00 Istanbul</option>
                        <option value="Asia/Jerusalem"  >+2:00 Jerusalem</option>
                        <option value="Europe/Kiev"  >+2:00 Kiev</option>
                        <option value="Europe/Minsk"  >+2:00 Minsk</option>
                        <option value="Europe/Riga"  >+2:00 Riga</option>
                        <option value="Europe/Sofia"  >+2:00 Sofia</option>
                        <option value="Europe/Tallinn"  >+2:00 Tallinn</option>
                        <option value="Europe/Vilnius"  >+2:00 Vilnius</option>
                        <option value="Europe/Moscow"  >+3:00 Moscow</option>
                        <option value="Europe/Volgograd"  >+3:00 Volgograd</option>
                        <option value="Asia/Baghdad"  >+3:00 Baghdad</option>
                        <option value="Asia/Kuwait"  >+3:00 Kuwait</option>
                        <option value="Africa/Nairobi"  >+3:00 Nairobi</option>
                        <option value="Asia/Riyadh"  >+3:00 Riyadh</option>
                        <option value="Asia/Tehran"  >+3:30 Tehran</option>
                        <option value="Asia/Baku"  >+4:00 Baku</option>
                        <option value="Asia/Muscat"  >+4:00 Muscat</option>
                        <option value="Asia/Tbilisi"  >+4:00 Tbilisi</option>
                        <option value="Asia/Yerevan"  >+4:00 Yerevan</option>
                        <option value="Asia/Kabul"  >+4:30 Kabul</option>
                        <option value="Asia/Karachi"  >+5:00 Karachi</option>
                        <option value="Asia/Tashkent"  >+5:00 Tashkent</option>
                        <option value="Asia/Kolkata"  >+5:30 Kolkata</option>
                        <option value="Asia/Kathmandu"  >+5:45 Kathmandu</option>
                        <option value="Asia/Almaty"  >+6:00 Almaty</option>
                        <option value="Asia/Dhaka"  >+6:00 Dhaka</option>
                        <option value="Asia/Rangoon"  >+6:30 Rangoon</option>
                        <option value="Asia/Bangkok"  >+7:00 Bangkok</option>
                        <option value="Asia/Jakarta"  >+7:00 Jakarta</option>
                        <option value="Asia/Chongqing"  >+8:00 Chongqing</option>
                        <option value="Asia/Hong_Kong"  >+8:00 Hong Kong</option>
                        <option value="Asia/Kuala_Lumpur"  >+8:00 Kuala Lumpur</option>
                        <option value="Australia/Perth"  >+8:00 Perth</option>
                        <option value="Asia/Singapore"  >+8:00 Singapore</option>
                        <option value="Asia/Taipei"  >+8:00 Taipei</option>
                        <option value="Asia/Ulaanbaatar"  >+8:00 Ulaan Bataar</option>
                        <option value="Asia/Urumqi"  >+8:00 Urumqi</option>
                        <option value="Asia/Seoul"  >+9:00 Seoul</option>
                        <option value="Asia/Tokyo"  >+9:00 Tokyo</option>
                        <option value="Australia/Adelaide"  >+9:30 Adelaide</option>
                        <option value="Australia/Darwin"  >+9:30 Darwin</option>
                        <option value="Australia/Brisbane"  >+10:00 Brisbane</option>
                        <option value="Pacific/Guam"  >+10:00 Guam</option>
                        <option value="Australia/Hobart"  >+10:00 Hobart</option>
                        <option value="Australia/Melbourne"  >+10:00 Melbourne</option>
                        <option value="Pacific/Port_Moresby"  >+10:00 Port Moresby</option>
                        <option value="Australia/Sydney"  >+10:00 Sydney</option>
                        <option value="Asia/Kamchatka"  >+11:00 Kamchatka</option>
                        <option value="Pacific/Auckland"  >+12:00 Auckland</option>
                        <option value="Pacific/Fiji"  >+12:00 Fiji</option>
                        </select>
                    </div>
                </div>
            </fieldset>

            <div class="extrawatch_signup_submit blue_button"><button onclick="validate();" type="button" tabindex="5">Create Account</button></div>
            <div class="one_store_message">One Magento store per ExtraWatch account</div>
        </form>
    </div>

    <div class="extrawatch_copy_wrapper">
        <div class="extrawatch_header">
            <h2>We <span class="love">&#9829;</span> answering questions.</h2>
        </div>

        <div class="extrawatch_copy">
            <h3>Why is my ExtraWatch data not in my dashboard?</h3>
            <p>Your data can be accessed via ExtraWatch.com, where we've built a site that aims to redefine how you experience your data. Finish creating your account to see it in action.</p>
            <h3>I'm not sure about trusting others with my business?</h3>
            <p>We've owned our own businesses and know how it feels - that's why we're certified by Digicert and McAfee. We also have a <a href="https://extrawatch.com/privacy" target="_blank">privacy policy</a> and <a href="https://extrawatch.com/terms" target="_blank">terms of service</a> that puts your priorities first.
            <div class="email_us">
                <h4>Email Us</h4>
                <p>support@extrawatch.com</p>
            </div>
            <div class="call_us">
                <h4>Call Us</h4>
                <p>+1 917 719 0255</p>
            </div>
        </div>
    </div>

</div>


<script type="text/javascript">
    function validate() {
        var postForm = new VarienForm('extrawatch_signupForm', true);
        postForm.submit();
    }
</script>
