<div class="content-header">
    <h3 class="head-dashboard">Create ExtraWatch Account</h3>
</div>

<div id="extrawatch_account_creation_error" class="extrawatch_account_creation_error">
  <div class="error_wrapper">
    <div class="error_notification">error notification icon</div>
    <div class="oops">
        <h1>We've hit a slight bump in the road.</h1>
    </div>
    <div class="wrapper">
      <div class="content first">
          <h3>Not sure what happened?</h3>
          <p>Get in touch, we'll get you up and running on ExtraWatch.</p>
      </div>
      <div class="content second">
          <h3>Connecting a test store?</h3>
          <p>Contact us for access to a full-featured test account.</p>
      </div>
    </div>
    <button class="email" onclick="setLocation('https://extrawatch.com/support')">support@extrawatch.com</button>
    <div class="phone">or call us +1 917 719 0255</div>
  </div>
</div>
