<div style="display:<?php echo $this->getShowHideString();?>; margin: 15px 0; width:100%; height:50px; text-align:center; font-size:8px; color:#4f4f4f; font-family:Helvetica, Arial, sans-serif; background:#fff957 url(http://extrawatch.s3.amazonaws.com/images/integration/2012/q1/magento/bg.png) repeat;">
    <h1 style="min-width:875px; font-weight:normal;"><img style="position:relative; top: 7px;" src="http://extrawatch.s3.amazonaws.com/images/integration/2012/q1/magento/done_check.png" alt="Complete" />
		&nbsp;&nbsp; Thank you for installing the &nbsp;
		<img  style="position:relative; top: 8px;" src="http://extrawatch.s3.amazonaws.com/images/integration/2012/q1/magento/extrawatch_id.png" alt="ExtraWatch" />
		&nbsp; extension. Now let&#8217;s finish setting up your store on our site. &nbsp;&nbsp; 
		<a href="<?php echo $this->getUrl('extrawatch/adminhtml_api/saveApiKey/'); ?>" onclick="window.open('<?php echo $this->getUrl('extrawatch/adminhtml_api/post/'); ?>', '_blank')">
			<img style="position:relative; top: 10px;" src="http://extrawatch.s3.amazonaws.com/images/integration/2012/q1/magento/finish_setup_btn.png" alt="Finish Setup" />
		</a>
	</h1>
</div>