<div class="content-header">
    <h3 class="head-dashboard">ExtraWatch Personal Assistant</h3>
</div>

<div id="extrawatch_personal_assistant" class="extrawatch_personal_assistant">
  <div>
    <div style="text-align:center">
        <h1>We're here to help you make the most out of your business.</h1>
    </div>
    <div style="text-align:center">
      <button class="email" onclick="setLocation('https://extrawatch.com/support')">support@extrawatch.com</button>
    </div>
    <div style="text-align:center" class="phone">or call us +1 917 719 0255</div>
  </div>
</div>
